### ISSUE TITLE
includeActual listener option

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/pdl#12]
Similar to includeScenarios, but default to true for includeActuals
https://github.com/usgs/pdl/blob/master/src/gov/usgs/earthquake/product/AbstractListener.java

**Comment by jmfee-usgs** [comment]
accept method is at:
https://github.com/usgs/pdl/blob/master/src/gov/usgs/earthquake/product/AbstractListener.java#L202

**Comment by jdbrown-USGS** [comment]
- Implemented in abstract listener class.
- Update documentation Located etc/documentation/userguide/configuration.html
- Write a unit test : configure a listener with include actual, verify accept product method includes or excludes actual products as expected.
