### ISSUE TITLE
Fix staging node 1

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/pdl#13]

**Comment by jdbrown-USGS** [comment]
- Do all the things.
- Sort out DMZ puppet environment.
- Make sure puppet runs with staging node 1. 
- Sync both staging nodes.
- Coordinate with Chris
- Ensure event pages and web service are working properly.

**Comment by jmfee-usgs** [comment]
The file system permissions and slave replication between acquisition and database have been fixed.  Now looking into syncing products.

**Comment by emartinez-usgs** [comment]
The latest ProductClient.jar needs to be deployed to the development nodes. The latest reviewed source code is available in the 1.10.0-rc branch in the project repository. Build and deploy to dev servers...

On node 1, you can do this manually to understand the process, however Puppet should be updated on node 2 so the same steps can be reliably performed on prod systems. The steps are as follows:

- Load schema into a separate database on acquisition server.
- Update PDL configuration...
  - Add a `scenario_indexer` to the list of top-level `listener`s
    - This should be very similar to the regular indexer configuration
    - Use a different value for `listenerIndexFile`
    - Use a different value for `index`
    - Use a different value for `storage`
  - Add a `scenario_indexer_index` section
    - This should be very similar to the `indexer_index`
    - Use an appropriate database name (see step 1 above)
    - Use the same credentials
  - Add a `scenario_indexer_storage` section
    - This should be very similar to the `indexer_storage`
    - Change the directory to be "scenario_indexer_storage" in the PDL data directory.

As a general note, be sure both regular and scenario indexers are configured to include the new MTIndexerModule (`modules` parameter) in addition to existing modules.
