### ISSUE TITLE
Update existing indexer modules to support internal and scenario products

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/pdl#14]
- Make sure indexer modules handle internal-TYPE TYPE-scenario internal-TYPE-scenario variants of a product type.

**Comment by jmfee-usgs** [comment]
Here's an example of where product type is checked:
https://github.com/usgs/pdl/blob/master/src/gov/usgs/earthquake/shakemap/ShakeMapIndexerModule.java#L43

**Comment by jmfee-usgs** [comment]
https://github.com/usgs/pdl/blob/master/src/gov/usgs/earthquake/dyfi/DYFIIndexerModule.java#L13

**Comment by emcwhirter-usgs** [comment]
What exactly is meant by "handle" here?

Should the ShakeMapIndexerModule make sure to include only "shakemap" types and then exclude shakemap-scenario? Or should that module add logic to handle "shakemap" differently than "shakemap-scenario"?

**Comment by emcwhirter-usgs** [comment]
Also, I see IndexerModules for "DYFI", "Shakemap" and "Tectonic Summary". Are those the only ones we need to update?

**Comment by jmfee-usgs** [comment]
"handle" means it should be able to process actual, scenario, and internal versions of these products; since their actual/scenario/internal-ness is the only difference, the contents are otherwise the same.

Those appear to be the only custom modules, and the moment tensor indexer module ( #9 ) should be implemented along these same lines.

**Comment by emcwhirter-usgs** [comment]
Is there any reason I can't use the `contains` method for java strings instead of using some combination of `startsWith` and `endsWith` craziness?

**Comment by jmfee-usgs** [comment]
Yes, there are other products like "shakemap-input" that may have issues.

**Comment by jmfee-usgs** [comment]
Since all indexer modules extend `DefaultIndexerModule`, this could be implemented as a base class method:
```java
  /**
   * Remove "internal-" prefix and "-scenario" suffix from product type".
   *
   * @param type
   *        product type.
   * @return base product type (without any known prefix or suffix).
   */
  String getBaseProductType(String type);
```

**Comment by emartinez-usgs** [comment]
Since you are using the `getBaseProductType` method now, we no longer need a `startsWith` check, instead just use a strict `equals` check. Also, some excessive whitespace around the DYFI type check.
