### ISSUE TITLE
Deploy latest versions to staging node 1

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/pdl#15]

**Comment by jdbrown-USGS** [comment]
- Depends on #13 being complete ( kinds of but not really ).

**Comment by ehunter-usgs** [comment]
It looked like there were only two applications that were out of sync with the dev02 node. I updated:
- hazdev-template
- earthquake-eventpages

**Comment by emartinez-usgs** [comment]
This appears complete so far. One major component remaining is PDL itself, which is not ready yet. TBD.

**Comment by emartinez-usgs** [comment]
This was done back in February.
