### ISSUE TITLE
code review for PDL v1.15.0

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/pdl#77]
Software best practices review or code review described here in item #5 - https://github.com/usgs/best-practices/blob/master/software/reviews.md#code-review 

Branch to be reviewed is 1.15.0-rc: https://github.com/usgs/pdl/tree/1.15.0-rc

**Comment by jpatton-USGS** [comment]
Would be nice to see the generated javadocs hosted on github.io or similar

**Comment by jpatton-USGS** [comment]
Would also like to see code coverage.

**Comment by jpatton-USGS** [comment]
Also, codacy or similar code checks, plus code style checks/linting

**Comment by mguy-usgs** [comment]
Overall it looked good, good code standards followed, good supporting documentation, good to see some tests, good exception handling

* add a code.json to the project to it will be on code.gov e.g. https://github.com/usgs/best-practices/blob/master/code.json

* add brief description of what this class is or does in the header javadoc at beginning or top of the file https://github.com/usgs/pdl/blob/f09cece51078976d4711bd7c128fcd708aa6fe24/src/gov/usgs/earthquake/momenttensor/MTIndexerModule.java#L2
* add method javadoc comments to public methods e.g. https://github.com/usgs/pdl/blob/f09cece51078976d4711bd7c128fcd708aa6fe24/src/gov/usgs/earthquake/momenttensor/MTIndexerModule.java#L30
e.g https://github.com/usgs/pdl/blob/19eb2de471064838e2a2629ce9a6b9e8878fb331/src/gov/usgs/earthquake/shakemap/GridXMLHandler.java#L110
* no javadoc or comments in this class/file https://github.com/usgs/pdl/blob/19eb2de471064838e2a2629ce9a6b9e8878fb331/src/gov/usgs/earthquake/shakemap/InfoXMLHandler.java#L10
* what is meant by the term "wedge" I know it is used in PDL, maybe add a sentence in this comment https://github.com/usgs/pdl/blob/19eb2de471064838e2a2629ce9a6b9e8878fb331/src/gov/usgs/earthquake/shakemap/ShakeMapIndexerWedge.java#L27

* hard coded URL is not sensitive (localhost is fine) but just confirming you want a hard coded URL? https://github.com/usgs/pdl/blob/19eb2de471064838e2a2629ce9a6b9e8878fb331/src/gov/usgs/earthquake/product/ProductDigest.java#L182

**Comment by mguy-usgs** [comment]
Add this class to license.md
https://github.com/usgs/pdl/blob/19eb2de471064838e2a2629ce9a6b9e8878fb331/src/gov/usgs/earthquake/shakemap/SimpleImageInfo.java#L14
