### ISSUE TITLE
Doesn't build on Ubuntu 16

### ISSUE THREAD

**Issue by ekalkan** [usgs/pdl#89]
On Ubuntu 16.04. Tried gradle assemble, build failed.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/tmp/pdl/build.gradle' line: 13

* What went wrong:
An exception occurred applying plugin request [id: 'org.ajoberstar.git-publish', version: '1.0.1']
> Failed to apply plugin [id 'org.ajoberstar.git-publish']
   > Could not create plugin of type 'GitPublishPlugin'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 36.86 secs

**Comment by jmfee-usgs** [comment]
Can you provide more information about your java environment?

I tried this in a ubuntu:16.04 docker container, using `openjdk-8-jdk-headless`, and am able to build the project as expected:
```
docker run --rm -it ubuntu:16.04 /bin/bash
# the rest runs inside the container
apt-get update
apt-get install -y git openjdk-8-jdk-headless
git clone https://github.com/usgs/pdl.git
cd pdl
./gradlew assemble
```

(Running tests require the current user to be able to "ssh localhost" non-interactively)

**Comment by jmfee-usgs** [comment]
Closing, because it appears possible to build as expected.
