### ISSUE TITLE
Moment tensor preferredness rules and indexer module

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/pdl#9]
This issue is a placeholder for discussion of proposed moment tensor preferredness rules to be implemented as an IndexerModule, to set default preferredness for moment tensor products contributed to comcat.

This ticket will require:
- Write an MTIndexerModule.java that will be used to summarize the MT products.
- Write unit tests for this new module.
- Deploy this module with a subsequent release of ProductClient.jar.
- Update client configurations to use this new module.

Several existing notes, in no particular order

1)
> New logic should be something like the following:
>  # MT from authoritative source (based on authoritative regions).
>  # If multiple MT from authoritative source, select based on MT type.
>    #- Mww > Mwc > Mwb > Mwr
>    #- Maybe more heirarchy TBD by Gavin.
>  # If multiple MT of a specific type from the authoritative source, use most recent product.

2)
> The following are harley's business rules for preferred MT by type.  For the Preferred Order by Catalog, the first one is most preferred, if a MT exists for none of the catalogs listed, but some catalog not listed, then most recent in time is Preferred (note I made this part up, harley left some holes in his logic), additionally, I think PDE and US will become one in the same...but again this is a place from which to start discussions IF still needed come November
> 
> MT Type   Preferred Order by Catalog
> -------   ---------------------------------------------------------
> Mww       1)Dupetel 2)PDE 3)US ("realtime" from hydra and/or gavin)
> Mwc       1)GCMT 2)US
> Mwr       1)Authoritative ANSS RSN 2)PDE 3)US (or real time)
> Mwb       1)PDE 2)US(or real time)

3)
> Suggest IndexerModule:
>  - points by type
>  - points by evaluation status (within a type)

**Comment by jmfee-usgs** [comment]
- default authoritative rules
  start at 1
  `+100 for authoritative contributor`
  `+ 50 for authoritative catalog`
  `+ 5 for contributor = catalog`

- points by type
    `+4 for type Mww`
    `+2 for type Mwc`
    `+1 for type Mwb`
    `+0 for type Mwr/Mw`

- penalty when type is outside it's valid magnitude range
  mwb magnitude is outside the range [5.5, 7]
  `-100 points for outside range`

- gcmt should be preferred within mwc
  `+56 for mwc from gcmt`

- duputel should be preferred within mww (this can be manually trumped during load)


Example:
Mww from NEIC in NEIC authoritative region
  1 + 100 + 50 + 5 + 4 = 160
Mwc ''
  1 + 100 + 50 + 5 + 2 = 158
Mwc from GCMT
  1 + 100 + 2 + 56 = 159

**Comment by emartinez-usgs** [comment]
- Update implementation of `getSupportLevel` to use the new `getBaseProductType` method similar to what is done in the `DYFIIndexerModule`.
- The GCMT bonus should be evaluated outside the `tensorType !== null` check.
- Comments are not always accurate for the adjoining code.

- Add documentation to about the new indexer module to the following pages:
  - etc/documentation/userguide/configuration.html
  - etc/documentation/userguide/indexer.html

- Update example configs to include new indexer module:
  - etc/examples/default/config.ini
  - etc/examples/indexer/conf/config.ini

- Add JavaDoc comment blocks to test methods clearly explaining what is being tested in each method.

**Comment by jdbrown-USGS** [comment]
Boots MWW type +56
